name: Check S3

on:
  workflow_dispatch:
jobs:
  check-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: List S3 buckets
        run: aws s3 ls
